name: Build Portable EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Kodu Indir
        uses: actions/checkout@v4

      - name: Node.js Kur (Bulutta)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Gerekli Paketleri Yukle
        run: npm install

      - name: EXE Dosyasini Olustur
        run: npm run build

      - name: EXE'yi Indirilebilir Yap
        uses: actions/upload-artifact@v4
        with:
          name: PayTak-Sanal-Ordek
          path: dist/*.exe
